Mudanças no Site Institucional
mia-ajuda/Institucional pull request #18
Opened 2021-08-23 21:00 UTC by Arthur-Matos

## Descrição 

Foram adicionadas as telas referentes ao documento disponibiliza pela Prof(a) Milene.

## Resolve (Issues)

Mudanças no Site Institucional [#196]

## PRs relacionados, se houver

## Tarefas gerais realizadas
* Criação e prototipagem das telas

2021-08-25 21:43 UTC, devsalula requested changes
@Arthur-Matos e @Sabanai104 parabéns pelo trabalho galera!

Porém queria pedir para vocês algumas mudanças:

1º - A imagem de ícone que tinha nessa página ela desapareceu. Conseguem verificar se erraram o caminho ou algo assim? Comparem como tá hoje em produção: https://miaajuda.netlify.app/team
![Screenshot from 2021-08-25 18-32-49](https://user-images.githubusercontent.com/35435199/130867876-1627d8de-92d2-4b54-a212-e520ccc1955f.png)

2º - A tela de contato está com o footer fora de posição. Uma coisa é que eu gostaria de sugerir para vocês juntarem essa página, junto com a página de Redes Sociais e diminuir a responsabilidade de ter um monte de botões na navbar
![Screenshot from 2021-08-25 18-32-57](https://user-images.githubusercontent.com/35435199/130868192-2b109164-2599-4a1f-9933-a224dd012377.png)

3º - Os botões da navbar estão estranhos. Diminuem o tamanho da fonte para ver se eles ficam menos tortos.
![Screenshot from 2021-08-25 18-33-31](https://user-images.githubusercontent.com/35435199/130868501-88c35b6c-7735-42cb-b889-d5851ca482cd.png)

4º - Essa página eu acho que ela pode ser simplificada e colocada na home page, com menos informações.
![Screenshot from 2021-08-25 18-35-37](https://user-images.githubusercontent.com/35435199/130868583-99cc275a-0233-483a-b219-6fba457eab3f.png)

2021-08-29 22:58 UTC, Arthur-Matos commented
> @Arthur-Matos e @Sabanai104 parabéns pelo trabalho galera!
> 
> Porém queria pedir para vocês algumas mudanças:
> 
> 1º - A imagem de ícone que tinha nessa página ela desapareceu. Conseguem verificar se erraram o caminho ou algo assim? Comparem como tá hoje em produção: https://miaajuda.netlify.app/team
> ![Screenshot from 2021-08-25 18-32-49](https://user-images.githubusercontent.com/35435199/130867876-1627d8de-92d2-4b54-a212-e520ccc1955f.png)
> 
> 2º - A tela de contato está com o footer fora de posição. Uma coisa é que eu gostaria de sugerir para vocês juntarem essa página, junto com a página de Redes Sociais e diminuir a responsabilidade de ter um monte de botões na navbar
> ![Screenshot from 2021-08-25 18-32-57](https://user-images.githubusercontent.com/35435199/130868192-2b109164-2599-4a1f-9933-a224dd012377.png)
> 
> 3º - Os botões da navbar estão estranhos. Diminuem o tamanho da fonte para ver se eles ficam menos tortos.
> ![Screenshot from 2021-08-25 18-33-31](https://user-images.githubusercontent.com/35435199/130868501-88c35b6c-7735-42cb-b889-d5851ca482cd.png)
> 
> 4º - Essa página eu acho que ela pode ser simplificada e colocada na home page, com menos informações.
> ![Screenshot from 2021-08-25 18-35-37](https://user-images.githubusercontent.com/35435199/130868583-99cc275a-0233-483a-b219-6fba457eab3f.png)

2021-08-29 23:01 UTC, Arthur-Matos commented
Fiz as alterações, mas tinha esquecido de Commitar, foi mal. Quanto a tela de 'Saiba Mais', tinha falado sobre isso com o sabanai, a gente tinha pensado em fazer exatamente isso, mas acabou que ficou desconexo com a home page e também acabava ficando poluída mesmo com o resumo das infos, por isso a gente resolver manter em uma aba separada

2021-08-30 20:54 UTC, devsalula requested changes
Beleza @Arthur-Matos. Queria pedir só uma última coisa. Conseguem corrigir as logos no carrossel da página de Saiba Mais? Elas ficaram meio esquisitas.

2021-09-01 23:06 UTC, devsalula approved these changes

2021-09-01 23:06 UTC, merged